name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Testing iOS app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test app
        run: xcodebuild -project KJVSearch/KJVSearch.xcodeproj -scheme "CI"  -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO clean test
