name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
  
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build app
        run: xcodebuild build-for-testing -scheme "CI" -project KJVSearch/KJVSearch.xcodeproj  -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        
    - name: Test app
      run: test-without-building -scheme "CI" -project KJVSearch/KJVSearch.xcodeproj  -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
